apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: kube-system # es habitual instalarlo en kube-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: bitnami-labs
        namespace: flux-system
      # opcional: fijar una versión concreta
      # version: ">=1.16.0-0"
  interval: 1h
  install:
    crds: CreateReplace
  values:
    # valores opcionales del chart (ajusta según necesidades)
    # serviceAccount:
    #   create: true