# clusters/microk8s-cluster/flux-system/gotk-sync.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  # ... (tus configuraciones existentes como interval, path, prune, sourceRef...)
  
  # --- AÑADE O ASEGÚRATE DE QUE ESTA SECCIÓN EXISTA ---
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: helm-controller
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: kustomize-controller
      namespace: flux-system
  # ---------------------------------------------------
