# clusters/microk8s-cluster/flux-system/sealed-secrets-infra.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets-infra # Nombre de esta nueva Kustomization en el clúster
  namespace: flux-system    # Donde se creará este recurso Kustomization
spec:
  interval: 10m
  path: ./clusters/microk8s-cluster/infra/sealed-secrets # Ruta en tu repositorio Git
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system # El nombre del recurso GitRepository que Flux está usando
  dependsOn:
    # Importante: Esto asegura que el HelmController (que gestiona HelmReleases)
    # esté completamente desplegado y sus CRDs registrados antes de intentar
    # aplicar el HelmRelease de sealed-secrets.
    - name: flux-system # Este nombre debe coincidir con el Kustomization principal de Flux
                        # (el que `flux bootstrap` crea y gestiona sus propios componentes).
                        # Puedes verificarlo con `kubectl get kustomization -n flux-system`.
  healthChecks:
    # Opcional: Esto añade una verificación de salud específica para el HelmRelease
    # asegurando que el controlador de sealed-secrets esté listo.
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: sealed-secrets-controller
      namespace: kube-system